
running 2 tests
test tests::unit_test::test_add_positive_numbers_unit ... ok
test tests::unit_test::test_add_negative_numbers_unit ... FAILED

failures:

---- tests::unit_test::test_add_negative_numbers_unit stdout ----
thread 'tests::unit_test::test_add_negative_numbers_unit' panicked at src/tests/unit_test.rs:13:9:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::unit_test::test_add_negative_numbers_unit

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s

